# Generated by Django 5.1.3 on 2024-11-16 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_remove_courses_student_courses_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Student Name'),
        ),
    ]
