# Generated by Django 5.1.3 on 2024-11-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='course',
        ),
    ]
